version: "3"
services:
  analysis:
    image: jlopezper/basic_reproduction_number:analysis
    ports:
      - "8787:8787"
    volumes:
      - ".:/home/r_devs/basic_reproduction_number"
    environment:
      DISABLE_AUTH: "true"
    working_dir: /home/r_devs/basic_reproduction_number